import { Platform, StyleSheet } from 'react-native';
import { hp, wp } from '@utils';

const createStyles = theme => {
  const styles = StyleSheet.create({
    mainContainer: {
      flex: 1,
      backgroundColor: theme.color.whiteBackground,
    },
    headerView: {
      marginTop: hp(2),
    },
    rowView: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: wp(2.5),
      paddingRight: wp(5),
      alignItems: 'center',
      marginVertical: hp(1),
    },
    allergyText: {
      color: theme.color.primaryColor,
    },
    allergyContainer: {
      marginLeft: wp(6),
    },
    searchRow: {
      flexDirection: 'row',
      width: wp(90),
      height: hp(6),
      alignSelf: 'center',
      justifyContent: 'space-around',
      alignContent: 'center',
      alignItems: 'center',
      marginBottom: hp(1),
    },
    tabView: {
      flexDirection: 'row',
      width: wp(90),
      height: hp(6),
      alignSelf: 'center',
      justifyContent: 'space-around',
      alignContent: 'center',
      alignItems: 'center',
      marginTop: hp(1),
    },
    filterText: {
      fontSize: hp(1.4),
      fontFamily: theme.family.semibold,
    },
    tabTitle: {
      fontSize: theme.size.medium,
      fontFamily: theme.family.semibold,
      marginHorizontal: wp(6),
    },
    selectedFilterText: {
      fontSize: hp(1.4),
      color: theme.color.whiteBackground,
      fontFamily: theme.family.bold,
    },
    noDataView: {
      height: hp(40),
      width: wp(90),
      justifyContent: 'center',
    },
    noResturant: {
      alignSelf: 'center',
      color: theme.color.disableButton,
      marginTop: hp(20),
      fontsSize: theme.size.medium,
    },
    flatlistContainerStyle: {
      marginLeft: wp(5),
      paddingRight: wp(8),
      paddingBottom: hp(10),
    },
    filterView: {
      borderWidth: 1,
      width: wp(42),
      paddingHorizontal: wp(1),
      paddingVertical: hp(0.7),
      borderRadius: theme.borders.radius4,
      borderColor: theme.color.inputFieldColor,
      backgroundColor: theme.color.inputFieldColor,
      justifyContent: 'center',
      alignItems: 'center',
    },
    inputText: {
      fontSize: theme.size.xsmall,
      color: theme.color.blackText,
      fontFamily: theme.family.bold,
    },
    avoidText: {
      fontSize: hp(1.6),
      color: theme.color.blackText,
      fontFamily: theme.family.semibold,
      marginLeft: wp(6),
      marginBottom: -hp(2),
    },
    avoidItemText: {
      fontSize: hp(1.6),
      color: theme.color.primaryColor,
      fontFamily: theme.family.semibold,
      marginLeft: wp(6),
    },
    selectedFilterView: {
      borderWidth: 1,
      width: wp(42),
      paddingHorizontal: wp(1),
      paddingVertical: hp(0.7),
      borderRadius: theme.borders.radius4,
      borderColor: theme.color.primaryColor,
      backgroundColor: theme.color.primaryColor,
      justifyContent: 'center',
      alignItems: 'center',
    },
    logoStyle: {
      height: wp(15),
      width: wp(45),
      alignSelf: 'center',
      // marginLeft: wp(-4),
    },
    leftIcon: {
      height: wp(15),
      width: wp(30),
      marginLeft: wp(-4),
    },
    marginRight: {
      marginRight: wp(1),
    },
    noPermission: {
      marginTop: hp(20),
      maxWidth: wp(70),
      alignSelf: 'center',
      textAlign: 'center',
    },
    avatarImg: {
      borderColor: theme.color.textWhite,
      borderWidth: 0.5,
      height: wp(22),
      width: wp(22),
      borderRadius: theme.borders.radius4,
    },
    userName: {
      marginTop: hp(2),
      fontFamily: theme.family.bold,
      maxWidth: wp(50),
    },
    loadingView: { flex: 1, justifyContent: 'center' },
    textEnable: {
      alignSelf: 'center',
      paddingHorizontal: wp(5),
      width: wp(50),
      alignItems: 'center',
      borderRadius: theme.borders.radius1,
      padding: wp(2),
      marginTop: hp(2),
      borderWidth: 1,
      borderColor: theme.color.primaryColor,
    },
    profileButton: {
      height: hp(5.2),
      width: wp(50),
      borderWidth: 1,
      borderColor: theme.color.primaryColor,
      borderRadius: theme.borders.radius4,
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
      backgroundColor: theme.color.whiteBackground,
      marginTop: hp(2),
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.2,
      shadowRadius: 1.41,

      elevation: 2,
    },
    modalText: {
      color: theme.color.primaryColor,
    },
    containerStyle: {
      height: 5,
      color: theme.color.whiteBackground,
      marginTop: Platform.OS == 'ios' ? -hp(2) : 0,
    },
    userBtn: {
      borderWidth: 0.5,
      borderColor: theme.color.placeholderText,
      borderRadius: theme.borders.radius4,
      height: wp(14),
      width: wp(14),
      backgroundColor: '#FFF',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.2,
      shadowRadius: 1.41,

      elevation: 1,
    },
    textNear: {
      fontFamily: theme.family.bold,
      color: theme.color.blackText,
      fontSize: theme.size.small,
    },
    textView: {
      fontFamily: theme.family.semibold,
      color: theme.color.primaryColor,
      fontSize: hp(2.3),
      alignSelf: 'center',
    },
    textViewWhite: {
      fontFamily: theme.family.semibold,
      color: theme.color.backgroundColor,
      fontSize: hp(2.3),
      alignSelf: 'center',
    },
    mapBtn: {
      width: wp(25),
      justifyContent: 'flex-end',
    },
    mapBtnWithBackground: {
      width: wp(25),
      justifyContent: 'flex-end',
      backgroundColor: theme.color.primaryColor,
      borderRadius: theme.borders.radius4,
    },
    inputContainer: {
      borderWidth: 1,
      borderColor: theme.color.inputFieldColor,
      backgroundColor: theme.color.inputFieldColor,
      borderRadius: theme.borders.radius4,
      paddingHorizontal: wp(2),
      height: hp(6),
      width: wp(62),
      alignSelf: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.2,
      shadowRadius: 1.41,
      elevation: 1,
      marginTop: hp(0.2),
    },
    inputContainerStyle: {
      width: wp(62),
    },
    map: { height: '100%', width: '100%' },
    mapView: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    modalView: {
      width: wp(70),
      backgroundColor: theme.color.whiteBackground,
      alignSelf: 'center',
      borderRadius: theme.borders.radius2,
      padding: wp(5),
      alignItems: 'center',
    },
  });
  return styles;
};
export default createStyles;
