import { hp, wp } from '@utils';
import { Platform, StyleSheet } from 'react-native';

const createStyles = theme => {
  const styles = StyleSheet.create({
    mainContainer: {
      flexGrow: 1,
      backgroundColor: theme.color.whiteBackground,
      paddingBottom: hp(5),
    },

    containerStyle: {
      height: 5,
      color: theme.color.whiteBackground,
      marginTop: Platform.OS == 'ios' ? -hp(2) : 0,
    },

    textTitle: {
      color: theme.color.whiteBackground,
      fontSize: theme.size.large,
      textTransform: 'capitalize',
    },
    backIcon: {
      size: wp(6),
      color: theme.color.whiteBackground,
    },
    rowView: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginHorizontal: wp(7),
    },
    noFood: {
      alignSelf: 'center',
      color: theme.color.disableButton,
      marginTop: hp(8),
      fontsSize: theme.size.medium,
    },
    resturantImage: {
      height: hp(30),
      width: wp(100),
      marginTop: hp(1),
    },
    modalLocationHeadingText: {
      color: theme.color.primaryColor,
      fontFamily: theme.family.semibold,
      textAlign: 'center',
      marginBottom: hp(1.5),
    },
    fullMenuText: {
      // marginTop: -hp(5),
      color: theme.color.primaryText,
      fontFamily: theme.family.semibold,
      textAlign: 'center',
      marginBottom: hp(1),
    },
    FeaturedText: {
      color: theme.color.primaryText,
      fontFamily: theme.family.semibold,
      textAlign: 'left',
      marginLeft: wp(7),
      marginTop: hp(1),
      marginBottom: -hp(1),
      fontSize: hp(1.6),
    },
    feedbackText: {
      color: theme.color.primaryText,
      fontFamily: theme.family.semibold,
      textAlign: 'left',
      marginLeft: wp(7),
      fontSize: hp(1.6),
      marginTop: hp(1),
    },
    loadingView: { flex: 1, justifyContent: 'center' },
    indicator: theme.color.primaryColor,

    map: { height: '100%', width: '100%' },
    mapView: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    modalView: {
      width: wp(70),
      backgroundColor: theme.color.whiteBackground,
      alignSelf: 'center',
      borderRadius: theme.borders.radius2,
      padding: wp(5),
      alignItems: 'center',
    },
    locationModalView: {
      width: wp(70),
      backgroundColor: theme.color.whiteBackground,
      alignSelf: 'center',
      borderRadius: theme.borders.radius2,
      padding: wp(5),
      // alignItems: 'center',
    },
    logoStyle: {
      height: wp(15),
      width: wp(45),
      alignSelf: 'center',
      // marginLeft: wp(-4),
    },
    leftIcon: {
      height: wp(15),
      width: wp(30),
      marginLeft: wp(-4),
    },
    marginRight: {
      marginRight: wp(1),
    },
    noPermission: {
      marginTop: hp(20),
      maxWidth: wp(70),
      alignSelf: 'center',
      textAlign: 'center',
    },
    avatarImg: {
      borderColor: theme.color.textWhite,
      borderWidth: 0.5,
      height: wp(22),
      width: wp(22),
      borderRadius: theme.borders.radius4,
    },
    profileButton: {
      height: hp(6),
      width: wp(50),
      borderWidth: 1,
      borderColor: theme.color.primaryColor,
      borderRadius: theme.borders.radius4,
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
      backgroundColor: theme.color.whiteBackground,
      marginTop: hp(2),
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.2,
      shadowRadius: 1.41,

      elevation: 2,
    },
    modalText: {
      color: theme.color.primaryColor,
    },
    headerView: {
      marginTop: hp(2),
    },
    rowView: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: wp(2.5),
      paddingRight: wp(5),
      alignItems: 'center',
      marginVertical: hp(1),
    },
    searchRow: {
      flexDirection: 'row',
      width: wp(90),
      height: hp(6),
      alignSelf: 'center',
      justifyContent: 'space-around',
      alignContent: 'center',
      alignItems: 'center',
      marginBottom: hp(1),
    },
    tabView: {
      flexDirection: 'row',
      width: wp(90),
      height: hp(6),
      alignSelf: 'center',
      justifyContent: 'space-around',
      alignContent: 'center',
      alignItems: 'center',
      marginVertical: -hp(0),
    },
    bottomBtn: {
      flexDirection: 'row',
      width: wp(90),
      height: hp(6),
      alignSelf: 'center',
      justifyContent: 'space-around',
      alignContent: 'center',
      alignItems: 'center',
      marginTop: hp(0.7),
    },
    userBtn: {
      borderWidth: 0.5,
      borderColor: theme.color.placeholderText,
      borderRadius: theme.borders.radius4,
      height: wp(14),
      width: wp(14),
      backgroundColor: '#FFF',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.2,
      shadowRadius: 1.41,

      elevation: 1,
    },
    textNear: {
      fontFamily: theme.family.bold,
      color: theme.color.blackText,
      fontSize: theme.size.small,
    },
    textView: {
      fontFamily: theme.family.semibold,
      color: theme.color.primaryColor,
      fontSize: hp(2.3),
      alignSelf: 'center',
    },
    textViewWhite: {
      fontFamily: theme.family.semibold,
      color: theme.color.backgroundColor,
      fontSize: hp(2.3),
      alignSelf: 'center',
    },
    mapBtn: {
      width: wp(25),
      justifyContent: 'flex-end',
    },
    mapBtnWithBackground: {
      width: wp(25),
      justifyContent: 'flex-end',
      backgroundColor: theme.color.primaryColor,
      borderRadius: theme.borders.radius4,
    },
    inputContainer: {
      borderWidth: 1,
      borderColor: theme.color.inputFieldColor,
      backgroundColor: theme.color.inputFieldColor,
      borderRadius: theme.borders.radius1,
      paddingHorizontal: wp(2),
      height: hp(6),
      width: wp(89),
      alignSelf: 'center',
      fontSize: hp(1.9),
      padding: wp(2),
    },
    inputContainerStyle: {
      width: wp(87),
    },
    selectedFilterView: {
      borderWidth: 1,
      paddingHorizontal: wp(1),
      paddingVertical: hp(0.7),
      borderRadius: theme.borders.radius4,
      borderColor: theme.color.primaryColor,
      backgroundColor: theme.color.primaryColor,
      width: wp(30),
    },
    inputText: {
      fontSize: hp(1.3),
      fontFamily: theme.family.semibold,
      color: 'black',
      textAlign: 'left',
      marginTop: hp(0.5),
    },
    commentInputText: {
      fontSize: hp(1.3),
      fontFamily: theme.family.semibold,
      color: 'black',
      textAlign: 'left',
      marginBottom: hp(1.5),
    },
    filterView: {
      borderWidth: 1,
      paddingHorizontal: wp(1),
      paddingVertical: hp(0.7),
      borderRadius: theme.borders.radius4,
      borderColor: theme.color.inputFieldColor,
      backgroundColor: theme.color.inputFieldColor,
      width: wp(28),
    },
    buttonActive: {
      borderWidth: 1,
      height: hp(4),
      borderRadius: theme.borders.radius4,
      borderColor: theme.color.primaryColor,
      backgroundColor: theme.color.primaryColor,
      width: wp(20),
    },
    buttonInactive: {
      borderWidth: 1,
      borderRadius: theme.borders.radius4,
      borderColor: theme.color.inputFieldColor,
      backgroundColor: theme.color.inputFieldColor,
      width: wp(29),
      height: hp(4),
    },
    postBtnSelected: {
      borderWidth: 1,
      paddingHorizontal: wp(1),
      paddingVertical: hp(0.7),
      borderRadius: theme.borders.radius4,
      borderColor: theme.color.primaryColor,
      backgroundColor: theme.color.primaryColor,
      marginBottom: hp(1.3),
      marginLeft: wp(2),
      alignSelf: 'center',
    },

    postBtnUnSelected: {
      borderWidth: 1,
      paddingHorizontal: wp(1),
      paddingVertical: hp(0.7),
      borderRadius: theme.borders.radius4,
      borderColor: theme.color.inputFieldColor,
      backgroundColor: theme.color.inputFieldColor,
      marginBottom: hp(1.3),
      alignSelf: 'center',
      marginLeft: wp(2),
    },
    includeBtnSelected: {
      borderWidth: 1,
      paddingHorizontal: wp(2),
      paddingVertical: hp(0.7),
      borderRadius: theme.borders.radius4,
      borderColor: theme.color.primaryColor,
      backgroundColor: theme.color.primaryColor,
      // marginTop: hp(1),
      height: hp(4),
    },

    includeBtnUnSelected: {
      borderWidth: 1,
      paddingHorizontal: wp(2),
      paddingVertical: hp(0.7),
      borderRadius: theme.borders.radius4,
      borderColor: theme.color.inputFieldColor,
      backgroundColor: theme.color.inputFieldColor,
      // marginTop: hp(1),
      height: hp(4),
    },
    selectedFilterText: {
      fontSize: hp(1.3),
      color: theme.color.whiteBackground,
      fontFamily: theme.family.bold,
      textAlign: 'center',
    },
    filterText: {
      fontSize: hp(1.3),
      fontFamily: theme.family.semibold,
      textAlign: 'center',
    },

    includePicBtn: {
      borderWidth: 1,
      paddingHorizontal: wp(2),
      paddingVertical: hp(0.7),
      borderRadius: theme.borders.radius4,
      borderColor: theme.color.primaryColor,
      backgroundColor: theme.color.primaryColor,
      // marginTop: hp(1),
      height: hp(4),
    },

    includePicBtnUnSelected: {
      borderWidth: 1,
      paddingHorizontal: wp(2),
      paddingVertical: hp(0.7),
      borderRadius: theme.borders.radius4,
      borderColor: theme.color.inputFieldColor,
      backgroundColor: theme.color.inputFieldColor,
      // marginTop: hp(1),
      height: hp(4),
    },
    selectedIncludeText: {
      fontSize: hp(1.3),
      color: theme.color.whiteBackground,
      fontFamily: theme.family.bold,
      textAlign: 'center',
    },
    unselectedIncludePicText: {
      fontSize: hp(1.3),
      fontFamily: theme.family.semibold,
      textAlign: 'center',
    },

    activeBtnText: {
      fontSize: hp(1.4),
      color: theme.color.whiteBackground,
      fontFamily: theme.family.bold,
      textAlign: 'center',
    },
    inactiveBtnText: {
      fontSize: hp(1.4),
      fontFamily: theme.family.semibold,
      textAlign: 'center',
      color: 'black',
    },
    locationText: {
      fontSize: hp(1.7),
      fontFamily: theme.family.semibold,
      textAlign: 'right',
      lineHeight: hp(3),
      width: wp(40),
    },
    modalLocationText: {
      fontSize: hp(1.7),
      fontFamily: theme.family.semibold,
      textAlign: 'left',
      lineHeight: hp(3),
      alignSelf: 'flex-start',
      textTransform: 'capitalize',
    },
    tabTitle: {
      fontSize: theme.size.medium,
      fontFamily: theme.family.semibold,
      marginHorizontal: wp(6),
    },

    resturantContainer: {
      flexDirection: 'row',
      marginHorizontal: wp(6),
      marginTop: hp(2),
    },
    logoImage: {
      width: wp(25),
      height: wp(25), // marginLeft: wp(-4),
    },
    locationHeadingText: {
      fontFamily: theme.family.semibold,
      color: theme.color.primaryColor,
      fontSize: hp(1.8),
      textAlign: 'right',
    },
    leftResturantContainer: {
      justifyContent: 'space-between',
      borderRightWidth: wp(1),
      alignItems: 'flex-start',
      width: wp(45),
      height: hp(16),
      borderRightColor: theme.color.blackText,
    },
    rightResturantContainer: {
      width: wp(45),
      height: hp(17),
      justifyContent: 'space-between',
      alignItems: 'flex-end',
    },
    resturantName: {
      fontFamily: theme.family.semibold,
      color: theme.color.primaryColor,
      fontSize: hp(2.3),
      marginTop: hp(1.2),
    },
    dropdownContainerStyle: {
      width: wp(87),
      alignSelf: 'center',
      height: hp(4.5),
    },
    ContainerInputStyle: {
      width: wp(87),
      alignSelf: 'center',
      height: hp(4.5),
      marginBottom: -hp(0.1),
      marginVertical: hp(1),
    },
    selectedFilterView: {
      borderWidth: 1,
      paddingHorizontal: wp(1),
      paddingVertical: hp(0.7),
      borderRadius: theme.borders.radius4,
      borderColor: theme.color.primaryColor,
      backgroundColor: theme.color.primaryColor,
      width: wp(28),
      marginBottom: -hp(0.5),
    },

    filterView: {
      borderWidth: 1,
      paddingHorizontal: wp(1),
      paddingVertical: hp(0.7),
      borderRadius: theme.borders.radius4,
      borderColor: theme.color.inputFieldColor,
      backgroundColor: theme.color.inputFieldColor,
      width: wp(28),
      marginBottom: -hp(0.5),
    },
    textMenu: {
      fontFamily: theme.family.semibold,
      color: theme.color.blackText,
      fontSize: hp(1.6),
      textAlign: 'center',
      marginTop: hp(2),
    },
    locationStyle: {
      top: 5,
      borderWidth: 1,
      alignSelf: 'center',
      borderColor: theme.color.inputFieldColor,
      backgroundColor: theme.color.inputFieldColor,
      borderRadius: theme.borders.radius4,
      height: hp(4.3),
      justifyContent: 'center',

      width: wp(88),

      // alignItems: 'center',
    },
    inputTextPlacholder: {
      marginLeft: wp(3),
      fontSize: hp(1.2),
      color: theme.color.placeholderText,
    },
    inputTextItem: {
      marginLeft: wp(3),
      fontSize: hp(1.2),
    },
  });
  return styles;
};
export default createStyles;
